export {
  saveUser,
  setToken,
  saveMenu,
  saveCredentials,
  loginFormIsValid,
  formIsRegistering,
  loginAuthenticated,
  saveOffer,
  saveOrder,
  saveQuantity,
  updateOrder,
  saveCategory,
  saveSocketID,
  saveClientSocketID,
} from "./login";
